[package]
name = "cers"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
dotenv = "0.15.0"
ratatui = "0.28.1"
term_size = "0.3.2"
winapi = { version = "0.3.9", features = ["psapi", "memoryapi"] }
