name: Rust

on:
  push:
    tags: [ "*" ]  # Triggers when pushing a tag (e.g., v1.0.0)

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Release Binary
      run: cargo build --release

    - name: Find Build Artifact
      id: artifact
      run: |
        echo "Searching for cers-* in target/release"
        FILE=$(dir /b target\release\cers-*.exe)
        echo "Found file: $FILE"
        echo "file=target/release/$FILE" >> $GITHUB_OUTPUT

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ steps.artifact.outputs.file }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
