name: Build and Release

on:
  push:
    tags:
      - '*'  # ✅ Only runs when you push a tag (like v1.0.0)

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build (Release)
      run: cargo build --release

    - name: Find Compiled File
      id: find_binary
      run: |
        for %%f in (target\release\cers-*.exe) do (
          echo Found %%f
          echo "artifact=%%f" >> %GITHUB_OUTPUT%
          goto :break
        )
        :break

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ steps.find_binary.outputs.artifact }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
